# This is a basic workflow to help you get started with Actions

name: Test Redact.md

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - id: test
        uses: mudlabs/github-action-redact.md@master
